name: Deploy public/ to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Se você já tem a pasta public/ pronta no repo, pode pular a parte de build.
      # Caso construa com Flask no CI, instale deps e rode "flask freeze".
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.11"
      # - run: |
      #     pip install -r dependencies.txt
      #     FLASK_APP=app flask freeze
      - run: |
          mkdir -p public
          touch public/.nojekyll   # evita interferência do Jekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
